KA-89
gamantha/kurir-app-server pull request #41
Opened 2018-02-07 00:43 UTC by bhirmbani

WIP
- [x] init upload endpoint works
- [ ] make bucket name: username/email, Key: ${prexif_by_upload_type}.${extension}
- [ ] conditional on uploadImg method to accomodate upload img based on purpose (id/user photo)
- [ ] make sure uploadImg returning s3 link to store at courierProposal table

2018-02-08 13:24 UTC, bhirmbani commented
ini yg paling update kayanya @andy-shi88

2018-02-12 12:50 UTC, andy-shi88 commented
wah, baru baca, paling update gimna maksudny? @bhirmbani

2018-02-13 12:38 UTC, andy-shi88 requested changes
ini coba kamu ambil dari develop dulu, resolve conflict, yang ada `this.service.proposeModel` pindahin ke proposal controller logicnya. untuk yang forgot password udah kurecover, kalau mau memudahkan resolve conflict, bisa di merge dulu

2018-02-13 12:38 UTC, andy-shi88 commented on controllers/UserController.js
> +      uniqueEmail = await this.service.findOne({
ini ada 2 kali query, bisa disatukan dengan operator OR

2018-02-13 12:38 UTC, andy-shi88 commented on controllers/UserController.js
> +            await this.service.proposeModel.update(
ini coba pas nanti resolve conflict dari develop di pindahkan ke proposal controller.

2018-02-14 00:01 UTC, bhirmbani commented
oke, yang branch forgot password sya merge dlu ya

2018-02-14 07:44 UTC, bhirmbani commented on controllers/UserController.js
> +      uniqueEmail = await this.service.findOne({
ini sengaja aku satukan, Dy. kalo pake operator OR, untuk menentukan message nya ga bisa nentuin yg sudah ada di db apakah email/username.

2018-02-14 13:22 UTC, bhirmbani commented
@andy-shi88 Minta review nya ya.

2018-02-19 12:17 UTC, andy-shi88 approved these changes

2018-02-19 12:22 UTC, andy-shi88 commented
@bhirmbani di merge aja kalau udah clear 👍

2018-02-20 03:54 UTC, merged